version: "3.7"
services:
  mirakurun:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kurukurumaware/mirakurun:latest
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    ports:
      - 40772:40772
      - 9229:9229
    devices:
      - /dev/px4video0:/dev/video0
      - /dev/px4video1:/dev/video1
      - /dev/px4video2:/dev/video2
      - /dev/px4video3:/dev/video3
    volumes:
      - /var/run/:/var/run/
      - /etc/mirakurun/config/:/app-config/
      - /var/lib/mirakurun/:/app-data/
    restart: always
